# Production

version: "3"

services:
  client:
    container_name: planet-client-prod
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    depends_on:
      - server
  server:
    container_name: planet-server-prod
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
